### ISSUE TITLE
app description is cut

### ISSUE THREAD

**Issue by julien-nc** [owncloud/marketplace-issues#1]
Nice to see info.xml markdown interpreted in app description. However, this description is cut after approximately 2000 characters.

**Comment by julien-nc** [comment]
As far as i can see, it's been solved. I let you close the issue if you confirm.

**Comment by hurradieweltgehtunter** [comment]
Yes this was extended to 4000 characters.
FYI: 
Title: 50 characters
Summary: 90 characters
Description: 4000 characters, markdown possible
