### ISSUE TITLE
ownCloud 8/9 API seems to provide wrong (older) app version

### ISSUE THREAD

**Issue by ghost** [owncloud/marketplace-issues#10]
Not quite sure if this is an issue with ownCloud itself, the Appstore API or the way that specific app is published. Please correct me if wrong posted

### Steps to reproduce

1. Have ownCloud 9.1.6 installed
2. Follow instructions at https://owncloud.org/blog/good-bye-apps-owncloud-com/ to add the appstore URL to the config.php
3. Login into my oC and open the app page
4. Open the "Integration" category

### Expected behaviour

The "Collabora Online App" will have version 1.1.23 as published at:

https://marketplace.owncloud.com/apps/richdocuments

### Actual behaviour

The "Collabora Online App" will has version 1.1.20 which is the oldest version published at:

https://marketplace.owncloud.com/apps/richdocuments

### Additional note

On the demo instance with oC 10 it seems 1.1.23 is provided:

https://demo.owncloud.org/index.php/apps/market/#/app/richdocuments

**Comment by ghost** [comment]
Same happens for Contacts and the Audio player:

https://marketplace.owncloud.com/apps/contacts
-> only 1.5.1 is available / provided, not the latest 1.5.2

https://marketplace.owncloud.com/apps/audioplayer
-> only 2.0.0 is available / provided, not the latest 2.0.2

**Comment by DeepDiver1975** [comment]
THX - I'll look into this asap ...

**Comment by ghost** [comment]
Just got a notification about two available updates for contacts and audioplayer. Looks like the fix from the private repo above did the trick. Thanks 👍
