### ISSUE TITLE
Wrong author info in ownCloud 8/9 API

### ISSUE THREAD

**Issue by ghost** [owncloud/marketplace-issues#11]
### Steps to reproduce

1. Have ownCloud 9.1.6 installed
2. Follow instructions at https://owncloud.org/blog/good-bye-apps-owncloud-com/ to add the appstore URL to the config.php
3. Login into my oC and open the app page
4. Open the "Multimedia" category (looks like this is the only category affected by this)

### Expected behaviour

The apps in the category should have the publisher name in their description

### Actual behaviour

The apps in the category have a ID as an author like e.g. 

Audio Player 2.0.0
by 5340929031e50e (GNU Affero General Public License-licensed)

GpxEdit 0.0.6
by 13ece0e721cd3f (GNU Affero General Public License-licensed)

Clicking on the author name leads to the following link:

https://marketplace.owncloud.com/publisher/5340929031e50e

which is a 404.

**Comment by DeepDiver1975** [comment]
the publisher did not set the profile public - this is why a 404 is returned. - no idea if there is much we can do .....

**Comment by ghost** [comment]
Hey, thanks for the background info.

I think the 404 is just an secondary issue and was just a note from my side (e.g. github is also returning a 404 for private repositories).

More important is the question, why such an ID is shown instead of the author name.

On oC 10/X that works and the name is shown:

https://demo.owncloud.org/index.php/apps/market/#/app/audioplayer

**Comment by hurradieweltgehtunter** [comment]
this is a random generated url slug for the publisher's page on the marketplace. One can edit it, but if not, the slug stays as the system generates it. It's not the ID.
Why this is displayed exactly is hard to tell. We're looking to get the marketplace working with OC 9.x but - unfortunately - it's not our main task. Sorry to tell you this. 
Let us know if you encounter any more problems.

**Comment by ghost** [comment]
Hey, no worry and thanks again for your reply. I think this is also just a cosmetic issue and doesn't affect any functionality. So no need to say sorry 😄

**Comment by hurradieweltgehtunter** [comment]
UX should be user-friendly so we're vowing to improve - even for cosmetics :)
Please close this issue if no further info needed.

**Comment by ghost** [comment]
Ok, so closing for now. Its documented here so it still can be re-opened if some one wants to tackle this.
