### ISSUE TITLE
Reset password buttom doesn't validate the email

### ISSUE THREAD

**Issue by davitol** [owncloud/marketplace-issues#13]
![email_empty](https://user-images.githubusercontent.com/10596560/29607460-9151ebc4-87f1-11e7-9d79-90d972915409.gif)

**Comment by hurradieweltgehtunter** [comment]
Thank you for pointing this out. Will be fixed asap

**Comment by hurradieweltgehtunter** [comment]
This is fixed and will be released with one of the next releases

**Comment by IljaN** [comment]
Fixed
