### ISSUE TITLE
"checked by us." text in upper left corner on mobile view

### ISSUE THREAD

**Issue by ghost** [owncloud/marketplace-issues#15]
See screenshot below, captured while viewing an app on the marketplace (doesn't matter which one) on Android with Firefox 56.

No idea where this text is coming from, can't find it in the source code of the webpage (maybe some 3rdparty javascript?)

![marketplace](https://user-images.githubusercontent.com/25050304/31587509-2fb7ab44-b1e3-11e7-98cc-fcbf84b254cf.png)

**Comment by hurradieweltgehtunter** [comment]
Thanks for filing this issue. Looked into it, seems to be a mislocated transform: translate css property.
I will take care of it.

**Comment by ghost** [comment]
Just also noticed that there is another "stray" text in the upper right corner when zooming in on the mobile device.

The text contains something like:

content the terms
Any of other copyright reason

**Comment by hurradieweltgehtunter** [comment]
Finally got fixed with the latest release and redesign
