### ISSUE TITLE
"beta" banner in upper left corner is hiding menu on mobile view

### ISSUE THREAD

**Issue by ghost** [owncloud/marketplace-issues#16]
When browsing on https://marketplace.owncloud.com/ with a mobile device the "beta" banner on the upper left corner is hiding the "dot" menu with the options to e.g. Sign up or browse categories.

![marketplace](https://user-images.githubusercontent.com/25050304/31587509-2fb7ab44-b1e3-11e7-98cc-fcbf84b254cf.png)

**Comment by hurradieweltgehtunter** [comment]
Thanks for naming this.
The beta label will get removed and the mobile views - which are partially buggy - will get an rework soon.

**Comment by patrickjahns** [comment]
Beta label has been removed - closing
