### ISSUE TITLE
Streamline Changelogs

### ISSUE THREAD

**Issue by JKawohl** [owncloud/marketplace-issues#17]
Somehow Changelogs for apps differ: 

![bildschirmfoto 2017-12-21 um 14 10 09](https://user-images.githubusercontent.com/12275313/34257087-b1cf0f88-e658-11e7-8602-91b40f1f5760.png)

vs.
![bildschirmfoto 2017-12-21 um 14 10 52](https://user-images.githubusercontent.com/12275313/34257123-cc73c05e-e658-11e7-803a-310e1c771b61.png)

**Comment by JKawohl** [comment]
imho it would make sense if the versioning on all apps would display the latest release on top

**Comment by patrickjahns** [comment]
@JKawohl 
That is for the developer to present - for the owncloud publisher, can you provide the apps where you noticed the differences?

**Comment by JKawohl** [comment]
That is for the user_ldap app: https://marketplace.owncloud.com/apps/user_ldap

all the others seem to display the latest releases always on top. For comparison: https://marketplace.owncloud.com/apps/guests

**Comment by patrickjahns** [comment]
That's a bug - semantic versioning is not used for listing the releases

**Comment by IljaN** [comment]
@JKawohl Should now be better with redesign, please feel free to reopen if something is wrong
