### ISSUE TITLE
Restrictions in which characters can be used in passwords?

### ISSUE THREAD

**Issue by Yetangitu** [owncloud/marketplace-issues#19]
It seems like the password for the marketplace is subject to some restrictions, e.g. it is not possible to use spaces. Why is this, and when will those restrictions be removed?

**Comment by IljaN** [comment]
Hi @Yetangitu,

thanks for reporting. This is a known bug the, restrictions will be removed soon.

**Comment by hurradieweltgehtunter** [comment]
This will be fixed in the next deployment, expected to happen on 2018/01/22

**Comment by IljaN** [comment]
Fixed
