### ISSUE TITLE
error PutObject when pi publish a release

### ISSUE THREAD

**Issue by zb2oby** [owncloud/marketplace-issues#21]
i have this error when i try to publish a new release. not significant changes in this release but it seems to be a memory error...

There was an error while processing your file:
Error executing "PutObject" on "https://storage.marketplace.owncloud.com/screenshots/groupalert-5abd44f1d0a48"; AWS HTTP error: Server error: PUT https://storage.marketplace.owncloud.com/screenshots/groupalert-5abd44f1d0a48 resulted in a 500 Internal Server Error response: <?xml version="1.0" encoding="UTF-8"?> XMinioStorageFullStorage backend has reached its min (truncated...) XMinioStorageFull (server): Storage backend has reached its minimum free disk threshold. Please delete a few objects to proceed. - <?xml version="1.0" encoding="UTF-8"?> XMinioStorageFullStorage backend has reached its minimum free disk threshold. Please delete a few objects to proceed./screenshots/groupalert-5abd44f1d0a483L1373L137

**Comment by zb2oby** [comment]
self resolved..

**Comment by patrickjahns** [comment]
@zb2oby 
Thanks for informing us - just letting you know, that you encountered a minor hiccup in our infrastructure.

We've escalated the issue to our devops team and will have another look into it.
