### ISSUE TITLE
Guests App Issue - Issue during sharing

### ISSUE THREAD

**Issue by RealGrimbi** [owncloud/marketplace-issues#23]
I have already specified the issue in the community forum:
https://central.owncloud.org/t/problems-with-guests-app-10-0-8-5/13751/4

**Comment by patrickjahns** [comment]
Your issue seems to be related to the guest app - not the marketplace as platform (https://marketplace.owncloud.com/) itself.

Please open the issue in https://github.com/owncloud/guests - also please describe the issue in detail in the issue tracker
