### ISSUE TITLE
Update Documentation Link for Ransomeware App

### ISSUE THREAD

**Issue by haukman** [owncloud/marketplace-issues#24]
I just discovered that the link to the documentation for the ransomeware app is not working (https://marketplace.owncloud.com/apps/ransomware_protection).

At the moment it points to: https://doc.owncloud.com/server/latest/admin_manual/configuration/server/security/ransomware-protection.html

The correct link would be: https://doc.owncloud.com/server/10.0/admin_manual/enterprise/ransomware-protection/

**Comment by DeepDiver1975** [comment]
PR to fix is open
