### ISSUE TITLE
Activity app: Dead link to documentation

### ISSUE THREAD

**Issue by va1entin** [owncloud/marketplace-issues#27]
The link to the docs for the Activity app is dead: https://marketplace.owncloud.com/apps/activity

I think this is the correct one, even though it's outdated: https://doc.owncloud.org/server/latest/admin_manual/configuration_server/activity_configuration.html

**Comment by DeepDiver1975** [comment]
Needs to ne adjusted in the Activity app

**Comment by DeepDiver1975** [comment]
-ne +be

**Comment by hurradieweltgehtunter** [comment]
Thanks for reporting.
Continued in https://github.com/owncloud/activity/issues/670

**Comment by jnweiger** [comment]
Fixed.
