### ISSUE TITLE
Unable to update from 0.2.5 to 0.3.0

### ISSUE THREAD

**Issue by wolkenschieber** [owncloud/marketplace-issues#28]
## Bug report

I'm unable to update the Market App from 0.2.5 to 0.3.0. The process fails due to failed code check.

### Steps to reproduce

1. Open Market App
1. Install Market Update

### Code-Check

Verifying the app using `occ` produces following output:
```
$ ./occ app:check-code market
ownCloud is in maintenance mode - no app have been loaded

Analysing /var/www/owncloud/apps/market/lib/Notifier.php
 1 errors
    line  107: OC_App - Static method of private class must not be called
Analysing /var/www/owncloud/apps/market/lib/MarketService.php
 2 errors
    line  281: OC_App - Static method of private class must not be called
    line  601: OC_App - Static method of private class must not be called
Analysing /var/www/owncloud/apps/market/lib/Controller/LocalAppsController.php
 1 errors
    line   46: OC_App - Static method of private class must not be called
App is not compliant
```

**Comment by IljaN** [comment]
Thanks for the report! Looking at the error it seems like this is a problem with the market app, so please feel free to create a issue here: https://github.com/owncloud/market  as this tracker is for the server-part of the marketplace. (https://marketplace.owncloud.com)

Please also state which ownCloud version you use.

**Comment by wolkenschieber** [comment]
Closing as issue has been submitted to wrong project. Sorry for that.

For those who are interessted, the issue at market ishttps://github.com/owncloud/market/issues/439.
