### ISSUE TITLE
PNG images as screenshots

### ISSUE THREAD

**Issue by pbek** [owncloud/marketplace-issues#29]
I tried to upload an updated package (just ownCloud version bump) of https://github.com/pbek/qownnotesapi, but the marketplace https://marketplace.owncloud.com/account/products/apps does not seem to accept screenshots.

```
There was an error while processing your file:
Could not load image: https://user-images.githubusercontent.com/1798101/51166088-9da33c00-18a2-11e9-9f3b-64d3b1022233.png
```

or

```
There was an error while processing your file:
Could not load image: https://raw.githubusercontent.com/pbek/qownnotesapi/develop/screenshot.png
```

Neither do local images in the package or no screenshot at all work, so currently I cannot upload an updated package.

Don't PNG images work as screenshots?

**Comment by IljaN** [comment]
Hi,

PNG should be possible. I just tried to run your image through the code which throws the error you are getting and it worked. Could you please try to upload the package again to see if it works? Maybe there was a connectivity issue with github. 

If the error still persists could you please send me the package you are trying to release for debugging? 

Thanks!

**Comment by pbek** [comment]
Thank you for the quick fix, it works now!
