### ISSUE TITLE
can't delete app release

### ISSUE THREAD

**Issue by julien-nc** [owncloud/marketplace-issues#3]
I guess the feature is coming but it is currently impossible to replace an app release, delete an entire app or even delete an app release.

**Comment by hurradieweltgehtunter** [comment]
Thx. 
We're on it. Storage System needs a little update, then deleting apps will be available.

**Comment by hurradieweltgehtunter** [comment]
Just giving you a short notice: Deleting of apps isn't that simple as we assumed in the first place. 
What you can do is de-activating apps and releases. To do so, go to "My products" in your account, click on the edit pen icon and change the state of an app or release to "unpublished". This hides your app and makes it not public available anymore.

**Comment by julien-nc** [comment]
Thanks for the advice.
