### ISSUE TITLE
API key Clipboard button needs feedback

### ISSUE THREAD

**Issue by PVince81** [owncloud/marketplace-issues#31]
### Steps

1. Login to marketplace
1. Go to https://marketplace.owncloud.com/account/organization
1. Click on the clipboard button.
1. Feel puzzled, this field looks disabled, doesn't it ?
1. Click on the clippboard button again: nothing happens.
1. Check local clipboard manager (on KDE, there's a plasma applet)
1. Ah, it did copy!

### Expected result
Visual feedback that the API key has been copied to clipboard, no surprises.

### Actual result
Frustration because it looks like the key was not copied when it did.

@hurradieweltgehtunter FYI

**Comment by PVince81** [comment]
in the actual scenario before the transcription I actually clicked the button at least 7 times

**Comment by hurradieweltgehtunter** [comment]
See the video below, there is a feedback.
Which browser are you using?

![mp](https://user-images.githubusercontent.com/16665512/55949940-07d63d80-5c54-11e9-9825-bea6dbc79691.gif)

**Comment by PVince81** [comment]
Firefox 66.0 on openSUSE Tumbleweed.

I didn't see the "Copied!" appearing.

On my env the field appears grayed out. This is a limited user, not admin.

**Comment by hurradieweltgehtunter** [comment]
if you inspect the input field, is there an attribute "readonly" or "disabled" ?

**Comment by PVince81** [comment]
it's `disabled="disabled"`

**Comment by hurradieweltgehtunter** [comment]
ah ok. it will get fixed with the next deployment

**Comment by hurradieweltgehtunter** [comment]
did you pull the latest master? The field should have a feedback and the attribute "readonly" instead of "disabled"

**Comment by PVince81** [comment]
this is on the production instance

**Comment by hurradieweltgehtunter** [comment]
> On my env the field appears grayed out. This is a limited user, not admin.

Ah I assumed you're on local 
Then it should be fixed with the next deployment

**Comment by jnweiger** [comment]
As of today (seen at production instance):

All input fields on that page are in light gray. the copy icon too. 
Not a strong visual cue in itself, but everything reacts nicely to clicking.
