### ISSUE TITLE
Download Button does not work in Safari

### ISSUE THREAD

**Issue by hosy** [owncloud/marketplace-issues#32]
I just tried to download an app, but the download button does not work on Safari. Tried it on Chrome and everything is working fine.

Safari 12.1
macOS 10.14.4

Just getting this error message in error console:

`[Error] Refused to display 'https://storage.marketplace.owncloud.com/apps/password_policy-2.0.2.tar.gz?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=8BXV1F3LCCSC9Z946NYU%2F20190507%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190507T191620Z&X-Amz-SignedHeaders=host&X-Amz-Expires=1200&X-Amz-Signature=e5a298a5000705cbe5ca43cb9bc6264577b4b06a7aff462a94ffde3693ad5fca' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.`

**Comment by hurradieweltgehtunter** [comment]
hey,
thanks for the notice. I will check this out in the next release

**Comment by hurradieweltgehtunter** [comment]
We released a new version of the marketplace frontend. Issue should be fixed.
Please reopen this issue if the problem persists.
