### ISSUE TITLE
Downloadcounter not working

### ISSUE THREAD

**Issue by Rello** [owncloud/marketplace-issues#33]
Hey Team,

can you please check the counter?
e.g. for the Audioplayer its stuck at 57045 since june

thank you

**Comment by DeepDiver1975** [comment]
we will look into this. THX for letting us know!

**Comment by Rello** [comment]
hello
any update?
the new version of AP is online and I am missing the OC statistics

**Comment by hurradieweltgehtunter** [comment]
@IljaN @DeepDiver1975 could you have a look please? Thx

**Comment by Rello** [comment]
so, any update?
or is the marketplace project stopped?
its a little demotivating to maintain an app without being able to see if its worth it at all :-(

**Comment by IljaN** [comment]
@Rello sorry for the delay we will take a look

**Comment by hurradieweltgehtunter** [comment]
any updates on this @IljaN ?

**Comment by Rello** [comment]
hmmm
:-(

**Comment by IljaN** [comment]
@Rello still on it

**Comment by Rello** [comment]
2 months for a counter?
This is a selling argument for OC.
I don´t get the point of not looking into this honestly...

**Comment by Rello** [comment]
So, after some frustration it seems OC is not interested in 3rd party app devs anymore
cheers

**Comment by felixboehm** [comment]
Hi @Rello,
we are interested and sorry for your frustration about the delay.
Please don't close issues when still open. This is first item on our backlog.

The download counter is triggered by the underlying storage system.
This is not ideal, as we can't fix it quite easy. We are rethinking this and find a good solution.
And yes, this will take some time. Thanks for understanding.

Also, having no working download counter is not a critical issue. 
We provided huge value on other fronts meanwhile. I hope you like them...

**Comment by hurradieweltgehtunter** [comment]
@Rello pls see https://github.com/owncloud/marketplace/pull/1107

**Comment by IljaN** [comment]
The marketplace repo is closed. But the fix was merged and will be deployed soon (tm)

**Comment by IljaN** [comment]
Fixed, sorry for the long delay :crying_cat_face:
