### ISSUE TITLE
Delete Accounts

### ISSUE THREAD

**Issue by Foggalong** [owncloud/marketplace-issues#35]
There's no way to delete ownCloud Marketplace accounts as is right now. I accidentally made a new account when trying to log into my old https://apps.owncloud.com account to update its password and now can't find anywhere in the settings to get rid of it.

**Comment by hurradieweltgehtunter** [comment]
Thank you. @IljaN could you delete his account manually?

**Comment by ghost** [comment]
Delete My Account

**Comment by Foggalong** [comment]
@hurradieweltgehtunter That I'm aware of this still hasn't happened.

There really should be a way for users to delete their own accounts or even just a designated email to request it through, rather than having to open a GitHub issue. This is supposed to be the kind of thing protected under GDPR.

**Comment by IljaN** [comment]
@Foggalong Sorry for the delay, your account was deleted

**Comment by Foggalong** [comment]
Thanks!
