### ISSUE TITLE
No failure indication in UI on processed app upload with errors

### ISSUE THREAD

**Issue by elie195** [owncloud/marketplace-issues#5]
Attempting to upload an app (using drag and drop) that contains a `<screenshot>` URL that returns a 404, will generate an error in the browser console (HTTP 400 in my case), but will not alert the user otherwise (the page shows that it's still processing the app).

**Comment by hurradieweltgehtunter** [comment]
We could reproduce this error and will fix this in the next release.
Thank you for telling us!

**Comment by hurradieweltgehtunter** [comment]
fixed.
The importer now checks the screenshot urls and displays an error message on fail.
Will be online in the next marketplace release (next few days)

Thank you for filing this issue.
