### ISSUE TITLE
Can't download apps

### ISSUE THREAD

**Issue by GTT8** [owncloud/marketplace-issues#6]
No app on the marketplace seem to be able to download. The result after trying to download an app through the browser is `Bad Gateway` as shown in the following image:

![screen shot 2017-06-20 at 03 56 16](https://user-images.githubusercontent.com/23523010/27313109-7090a536-556c-11e7-8511-cfe5bc2670f0.png)

And if the app is being downloaded form the Owncloud Server, the result is `No Marketplace Connection`

**Comment by thomasrudin** [comment]
same here:

https://storage.marketplace.owncloud.com/apps/contacts-1.5.2.tar.gz?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=8BXV1F3LCCSC9Z946NYU%2F20170620%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20170620T054730Z&X-Amz-SignedHeaders=host&X-Amz-Expires=1200&X-Amz-Signature=906a62a8b10d5c603e27506f5c94eee976863a179e182bde06c358ba56c773c9

**Comment by PVince81** [comment]
@tboerger

**Comment by tboerger** [comment]
Sorry, the used storage application had an issue. Everything should be up and running fine again.

**Comment by DeepDiver1975** [comment]
confirmed  -works again - thx
