### ISSUE TITLE
Allow AGPL-compliant licenses

### ISSUE THREAD

**Issue by bud-mo** [owncloud/marketplace-issues#9]
It would be very useful to consider other licenses than AGPL.
After a similar discussions (here: https://github.com/nextcloud/appstore/issues/28) we have found these licenses which are compatible:

- mpl
- apache

I suggest to allow these licenses into the store.

**Comment by hodyroff** [comment]
Thanks for your request. While we could and will allow this, after review, it is not possible, without our approval to have an app on top of any fork of ownCloud which has a different license then AGPLv3. We see any such app as a derivative of the ownCloud code base.
(Disclosure: I am not a lawyer but an authorized representative of the copyright holder to the ownCloud code base as its covered under the contributor license agreement (CLA)).

**Comment by DeepDiver1975** [comment]
both license will be soon available - in order to use them please get in touch with @hodyroff - THX

**Comment by bud-mo** [comment]
Thank You for the support, I will get in touch with @hodyroff
